services:
  postgresql:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    env_file: ".env"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d accounts_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: ".env"
    restart: unless-stopped

volumes:
  postgres_data: