spring.application.name=banking-transaction-service
server.port=8080

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:bank_db_transaction
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http.converter=DEBUG

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Optional: Enable H2 Console for viewing the database (very useful for development)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Configurações do Kafka
spring.kafka.bootstrap-servers=localhost:9092 # Endereço do seu broker Kafka

# Tópicos Kafka para os eventos
kafka.topics.transaction-approved=transaction.approved
kafka.topics.transaction-rejected=transaction.rejected
kafka.topics.refund-approved=refund.approved
kafka.topics.refund-failed=refund.failed